### ISSUE TITLE
How did you hear about good call "other" field has no open text option

### ISSUE THREAD

**Issue by gleaderrose** [good-call-nyc/landing-page#20]
On https://goodcall.nyc/sign-up

If "other" is chosen from the "how did you hear about good call" dropdown, text field should appear so user can enter what "other" place they heard about good call. 

http://recordit.co/O4swbb19rU/gif/notify

**Comment by nstepheyim** [comment]
we made the decision to not have it because:

1. simplicity UI and dev sake haha
2. there are already so many options that we don't think many people would actually click "other"

**Comment by data-doge** [comment]
@gleaderrose ok to close issue?

**Comment by gleaderrose** [comment]
Yup, sounds good. Can always add later if lots of people are picking other,
but no need now.
