### ISSUE TITLE
mobile DoB dropdown returns to homepage when clicked

### ISSUE THREAD

**Issue by nstepheyim** [good-call-nyc/landing-page#21]
mobile portrait - 

On the registration page, when you are trying to select your DoB, if the month is January, the user is brought back to the homepage. The drop down sits on top of the Good Call logo and the tap is being picked up as a tap on the home logo instead. 

Bug recorded below:
http://g.recordit.co/uG0NPNVtt3.gif

**Comment by data-doge** [comment]
fixed in https://github.com/good-call-nyc/landing-page/pull/19/commits/1c2ca4e93b09eec991b63acf19d901362f634b98

![example](http://g.recordit.co/cAUaIAGCXk.gif)

will be deployed along with https://github.com/good-call-nyc/landing-page/pull/19

closing this issue for now
